version: "3.8"
services:
  rails:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /node_modules
    stdin_open: true
    tty: true
    command: sh -c "rm -f tmp/pids/server.pid && bundle install -j4 && bundle exec rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.22
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: infra-test
volumes:
  db-data: